
# This is the user-interface definition of a Shiny web application.

library(shiny)

shinyUI(fluidPage(
    
    navbarPage(
        "Emancipation",
        tabPanel("Model",
                 # Sidebar with slider input
                 sidebarLayout(
                     sidebarPanel(
                         sliderInput("topSalary",
                                     "Top position salary:",
                                     min = 10,
                                     max = 50,
                                     value = 30),
                         sliderInput("partBenefit",
                                     "Benefit of part-time over full-time:",
                                     min = 1,
                                     max = 5,
                                     value = 1),
                         sliderInput("rankShift",
                                     "Number of men preferred over a woman:",
                                     min = 0,
                                     max = 50,
                                     value = 1)
                     ),
                     
                     # Show a plot
                     mainPanel(
                         plotOutput("laborPlot")
                     )
                 )),
        tabPanel("Explanation",
                 
                 h2("Summary"),
                 
                 p("This economy has 100 people, equally divided over
                   women and men, with differing levels of talent.
                   Companies have 10 top positions available. More 
                   talent increases the odds of getting a top position.
                   Top positons pay better than other jobs."),
                 p("Given this difference people decide either to
                   work full-time or part-time. Only when working
                   full-time you can reach a top position. On the
                   other hand people prefer part-time work over
                   full-time work if the odds of reaching the top
                   are too low."),
                 p("Lastly, you can determine how many men are preferred
                   over a woman given similar talent."),
                 p("The graph then presents you with the number and share 
                   of men and women in top positions, full-time and 
                   part-time jobs."),
                 
                 h2("Details"),
                 
                 h3("Top position lottery"),
                 p("The economy has 100 persons with talent 1 to 100.
                   Each point of talent counts as a lottery ticket.
                   The lottery determines who gets the available top
                   positions. The more tickets you have, the better
                   your odds. The more participants in the lottery,
                   the worse your odds."),
                 p("To account for this, two calculations have been
                   made. The first gives a table with the odds of 
                   getting a top position when the person is the least
                   talented entrant, assuming all more talented people 
                   already entered. The second calculation gives the
                   odds for all other persons, given the least talented
                   entrant."),
                 p("These two sets of odds were generated by calculating
                   lottery outcomes, given the above assumptions about
                   talent and entrants. The odds are hence pre-generated,
                   and loaded into memory."),
                 
                 h3("Deciding between part-time and full-time"),
                 p("All 100 persons in the economy decide to work
                   part-time or full-time. You only enter the top
                   position lottery when you work full-time.
                   Moreover, part-time work is perceived as more
                   rewarding than full-time work, except for the
                   (option) value of the lottery ticket."),
                 p("To determine who enters the lottery, a simple
                   calculation is made: divide the net benefit
                   of part-time work by the reward for a top position.
                   This number is the probability that a person will 
                   accept full-time work to be able to enter the 
                   lottery."),
                 p("The calculated odds, given the last entrant are also
                   the expected value of getting a top job. The odds of 
                   all persons add up to 10, the number of available top 
                   positions."),
                 
                 h3("Men versus women"),
                 p("Up to this point, sex did not matter. In the final
                   step the model assigns a gender to each person.
                   The input slider asks you to put the difference between
                   men and women with the same talent. With discrimination 
                   of 1 talent point all men are put one position ahead of 
                   a woman:
                   the most \"talented\" person is a man, the next a woman
                   all the way down to the least \"talented\" person, a
                   woman.
                   If the difference increases, each time all men move up
                   one position, until a difference of 50 where even the
                   least talented man is perceived as having more talent
                   than the most talented woman."),
                 p("This ranking of men and women is then combined with
                   the pre-generated odds to make the graphs."),
                 
                 h2("Some considerations"),
                 
                 p("This approach does not account for real differences
                   in preferences among men and women. Furthermore,
                   it is very stylized, though it does show how expected
                   market outcomes influence decisions that in turn
                   influence final outcomes. If a group, here women, 
                   believes that it is being discriminated against, it 
                   will adjust its behavior accordingly, possibly 
                   entrenching skewed outcomes."),
                 
                 h2("Use"),
                 p("This model is used in the article at:"),
                 a(href="http://me.vanelp.com/post/emancipation-and-causation/"
                   , "My Economiscs: Emancipation and causation"),
                 p()
        )))
)
